from typing import Callable, List

from typing import overload

class Tensor:
    @overload
    def __init__(self, input_data: List[float], input_shape: List[int] = ..., input_stride: List[int] = ..., offset: int = ...) -> None: ...
    @overload
    def __init__(self, other_view: Tensor, input_shape: List[int] = ..., input_stride: List[int] = ..., offset: int = ...) -> None: ...
    def binary_element_wise_op(self, arg0: Tensor, arg1: Callable[[float,float],float]) -> Tensor: ...
    def get_buffer(self) -> List[float]: ...
