import _pysiclib.linalg

class LinearModel:
    def __init__(self, *args, **kwargs) -> None: ...
    def fit_model(self, arg0: _pysiclib.linalg.Tensor, arg1: _pysiclib.linalg.Tensor) -> None: ...
    def predict(self, arg0: _pysiclib.linalg.Tensor) -> _pysiclib.linalg.Tensor: ...
